name: CI
on: 
  pull_request:
    branches:
      - develop
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: sfourm/continuous-integration:latest  
